version: "3.8"

services:
  postgres :
    image: prostgres:16
    container_name: my_prostgres
    environment:
      PROSTGRES_USER: prostgres
      POSTGRES_PASSWORD: kuzykuzn
      POSTGRES_DB: postgres
    volumes:
      -pg_data:/var/lib/prostgresql/data
    restart: unless-stopped

  cpp_app:
    build: .
    container_name: my_cpp_app
    depends_on:
      - prostgres
    restart: unless-stopped
    ports:
      - "8080:8080"
    enviroment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: kuzykuzn
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8888:80"
    restart: unless-stopped

volumes:
  pg_data: